### ISSUE TITLE
badness on high yaw

### ISSUE THREAD

**Issue by sthalik** [uricamic/flandmark#20]
High face yaw causes false positive detections which don't correspond to what's in the image.

Trying to guard against it by guessing yaw and skipping flandmark_detect invocation but it's kludgy and doesn't work anyway.

**Comment by uricamic** [comment]
Yaw angle with big deviation from near-frontal can be handled by learning new detector, e.g. for full profile and then switching between detector's dependent on the yaw angle estimation.

**Comment by sthalik** [comment]
Solution I chose is to ignore poses where the model and the flandmark detector's rotation differ by more than a threshold amount.

Critical yaw angle value is problematic to estimate as it depends on pitch too.
